### ISSUE TITLE
tutorial 5 issues

### ISSUE THREAD

**Issue by pet-e** [MI-AFP/tutorials#11]
Both in tutorial #5.

## 1. `(><)` swaps arguments in the result

https://github.com/MI-AFP/tutorials/blob/master/tutorials/05_functions-typeclasses.md#own-operators

```haskell
Prelude> (><) xs ys = reverse xs ++ reverse ys
Prelude> (><) "abc" "xyz"
"zyxcba"
```

but the correct result should be
`cbazyx`

## 2. parametre -> parameter

in multiple places

**Comment by MarekSuchanek** [comment]
Thanks, will be fixed...
