### ISSUE TITLE
01-FP_Env IntelliJ Haskforce link broken

### ISSUE THREAD

**Issue by chovanecm** [MI-AFP/tutorials#22]
Hi,
the Haskforce domain you are referencing from the first tutorial has expired.
Perhaps you can change it to their [github repo](https://github.com/carymrobbins/intellij-haskforce)?
https://github.com/MI-AFP/tutorials/blob/master/tutorials/01_fp-env.md

**Comment by MarekSuchanek** [comment]
Hello, looks like the working now again. To be sure I added the link to repo as you suggested. Thanks!
